#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

SMTP_HOST = smtp_settings['host']
SMTP_PORT = smtp_settings['port']
SMTP_USERNAME = smtp_settings['username']
SMTP_PASSWORD = smtp_settings['password']
SMTP_ENCRYPTION = smtp_settings['encrypt_smtp']
SMTP_TLSVERIFY = smtp_settings['tls_verify']

host = data.get('host')


opn_config = {
    "MAIL_MAILER": "smtp",
    "MAIL_HOST": SMTP_HOST,
    "MAIL_PORT": SMTP_PORT,
    "MAIL_USERNAME": SMTP_USERNAME,
    "MAIL_PASSWORD": SMTP_PASSWORD,
    "MAIL_ENCRYPTION": SMTP_ENCRYPTION,
    "MAIL_FROM_ADDRESS": SMTP_USERNAME,
    "MAIL_FROM_NAME": SMTP_USERNAME,
    "FRONT_URL": f"https://{host}",
}
agent.write_envfile("opnform-api.env", opn_config)

# NUXT_PUBLIC_APP_URL: ${NUXT_PUBLIC_APP_URL:-/}
#       NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE:-/api}
#       NUXT_PRIVATE_API_BASE: http://ingress/api

opn_ui_config = {
    "NUXT_PUBLIC_APP_URL": f"https://{host}",
    "NUXT_PUBLIC_API_BASE": "/api",
    "NUXT_PRIVATE_API_BASE": f"https://{host}/api",
}
agent.write_envfile("opnform-ui.env", opn_ui_config)

#agent.dump_env()
